#!/bin/bash

# Ensure correct usage
if [ "$#" -lt 1 ]; then
    echo "Usage: ./django <create|delete|run|list-projects> [project_name]"
    exit 1
fi

COMMAND=$1
PROJECT_NAME=$2
DPM_NAME=django_project_mgmt.py
DPM_DIR=./automate/bin
DPM_EXE=$DPM_DIR/$DPM_NAME
PYTHON_EXE=python

# Read PROJECT_BASE_DIR from config.ini
CONFIG_FILE=./config.ini
PROJECT_BASE_DIR=$(awk -F' *= *' '$1=="PROJECT_BASE_DIR"{print $2}' "$CONFIG_FILE")

# Fallback to default if config.ini is missing
if [ -z "$PROJECT_BASE_DIR" ]; then
    PROJECT_BASE_DIR="env/dev"
    echo "PROJECT_BASE_DIR not found in $CONFIG_FILE. Using default value: $PROJECT_BASE_DIR"
fi

PROJECT_PATH="$PROJECT_BASE_DIR/$PROJECT_NAME"

# Validate commands
if [[ "$COMMAND" != "create" && "$COMMAND" != "delete" && "$COMMAND" != "run" && "$COMMAND" != "list-projects" ]]; then
    echo "Invalid command: $COMMAND"
    echo "Usage: ./django <create|delete|run|list-projects> [project_name]"
    exit 1
fi

if [ "$COMMAND" == "create" ]; then
    $PYTHON_EXE $DPM_EXE create "$PROJECT_NAME"

    if [ $? -eq 0 ]; then
        echo -e "#!/bin/bash\npython manage.py runserver" > "$PROJECT_PATH/m3"
        chmod +x "$PROJECT_PATH/m3"
        echo "Shortcut 'm3' created in $PROJECT_PATH"
    fi
fi

if [ "$COMMAND" == "delete" ]; then
    $PYTHON_EXE $DPM_EXE delete "$PROJECT_NAME"
fi

if [ "$COMMAND" == "run" ]; then
    if [ ! -d "$PROJECT_PATH" ]; then
        echo "Error: Django project '$PROJECT_NAME' does not exist."
        exit 1
    fi

    if [ ! -f "$PROJECT_PATH/m3" ]; then
        echo "Error: Shortcut 'm3' not found in $PROJECT_PATH"
        exit 1
    fi

    cd "$PROJECT_PATH"
    ./m3
fi

# LIST PROJECTS
if [ "$COMMAND" == "list-projects" ]; then
    if [ ! -d "$PROJECT_BASE_DIR" ]; then
        echo "Error: Base directory '$PROJECT_BASE_DIR' does not exist."
        exit 1
    fi

    # Count the number of directories (projects) inside the base directory
    PROJECT_COUNT=$(find "$PROJECT_BASE_DIR" -mindepth 1 -maxdepth 1 -type d | wc -l)
    
    echo "Total Django projects in '$PROJECT_BASE_DIR': $PROJECT_COUNT"
    
    # List all directories inside the base directory
    #echo "Projects in '$PROJECT_BASE_DIR':"
    ls -d "$PROJECT_BASE_DIR"/* 2>/dev/null | xargs -n 1 basename
fi