#!/bin/bash

if [ "$#" -ne 1 ]; then
    echo "Usage: . ./goto <project_name>"
else

    PROJECT_NAME=$1
    PROJECT_BASE_DIR="env/dev"
    PROJECT_PATH="$PROJECT_BASE_DIR/$PROJECT_NAME"

    if [ ! -d "$PROJECT_PATH" ]; then
        echo "Error: Project '$PROJECT_NAME' does not exist."
        
    else
        cd "$PROJECT_PATH"
    fi

fi
